<?php

namespace Etrias\PaazlConnector\SoapTypes;

class PackagingTypeType
{
    const FEDEX_10_KG_BOX = 'FEDEX_10_KG_BOX';
    const FEDEX_25_KG_BOX = 'FEDEX_25_KG_BOX';
    const FEDEX_BOX = 'FEDEX_BOX';
    const FEDEX_ENVELOPE = 'FEDEX_ENVELOPE';
    const FEDEX_TUBE = 'FEDEX_TUBE';
    const YOUR_PACKAGING = 'YOUR_PACKAGING';
    const UPS_LETTER = 'UPS_LETTER';
    const CUSTOMER_SUPPLIED_PACKAGE = 'CUSTOMER_SUPPLIED_PACKAGE';
    const TUBE = 'TUBE';
    const PAK = 'PAK';
    const UPS_EXPRESS_BOX = 'UPS_EXPRESS_BOX';
    const UPS_25_KG_BOX = 'UPS_25KG_BOX';
    const UPS_10_KG_BOX = 'UPS_10KG_BOX';
    const SMALL_EXPRESS_BOX = 'SMALL_EXPRESS_BOX';
    const MEDIUM_EXPRESS_BOX = 'MEDIUM_EXPRESS_BOX';
    const LARGE_EXPRESS_BOX = 'LARGE_EXPRESS_BOX';
    const VAN_SPREUWEL_COLLI = 'VAN_SPREUWEL_COLLI';
    const VAN_SPREUWEL_BLOCKPALLET = 'VAN_SPREUWEL_BLOCKPALLET';
    const VAN_SPREUWEL_EUROPALLET = 'VAN_SPREUWEL_EUROPALLET';
    const VAN_SPREUWEL_TROLLEY = 'VAN_SPREUWEL_TROLLEY';
}

